version: 2.1
orbs:
  node: circleci/node@4.1.0

parameters:
  build-react-app-1:
    type: boolean
    default: false
  build-react-app-2:
    type: boolean
    default: false

jobs:
  echo-1:
    docker:
      - image: cimg/node:12.20.0
    steps:
      - checkout
      - run:
          command: cd project/react-app-1
          name: go to react-app-1 directory
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
  echo-2:
    docker:
      - image: cimg/node:12.20.0
    steps:
      - checkout
      - run:
          command: cd project/react-app-2
          name: go to react-app-1 directory
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests

workflows:
  build-server:
    when: << pipeline.parameters.build-react-app-1 >>
    jobs:
      - echo-1
  build-client:
    when: << pipeline.parameters.build-react-app-2 >>
    jobs:
      - echo-2