version: 2.1
orbs:
  node: circleci/node@4.1.0

parameters:
  build-react-app-1:
    type: boolean
    default: false
  build-react-app-2:
    type: boolean
    default: false

executors:


jobs:
  echo-1:
    docker:
      - image: cimg/node:12.20.0
    # working_directory: ~/project/react-app-1
    steps:
      - checkout
      - run:
          command: cd react-app-1 && yarn run install
          name: Run YARN install
      # - node/install-packages:
      #     pkg-manager: yarn
      - run:
          command: cd react-app-1 && yarn run test
          name: Run YARN tests
  echo-2:
    docker:
      - image: cimg/node:12.20.0
    # working_directory: ~/project/react-app-2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests

workflows:
  build-server:
    when: << pipeline.parameters.build-react-app-1 >>
    jobs:
      - echo-1
  build-client:
    when: << pipeline.parameters.build-react-app-2 >>
    jobs:
      - echo-2